[package]
name = "aoc-2022-d3"
authors = ["pan93412"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delegate-attr = "0.2.9"
